steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_AR_HOST}/$PROJECT_ID/${_AR_REPO}/mi-medcare-api:$COMMIT_SHA",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["push", "${_AR_HOST}/$PROJECT_ID/${_AR_REPO}/mi-medcare-api:$COMMIT_SHA"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "mi-medcare-api",
        "--image",
        "${_AR_HOST}/$PROJECT_ID/${_AR_REPO}/mi-medcare-api:$COMMIT_SHA",
        "--region",
        "asia-south1",
        "--allow-unauthenticated",
        "--min-instances",
        "1",
        "--max-instances",
        "10",
        "--port",
        "8080"
      ]

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - "${_AR_HOST}/$PROJECT_ID/${_AR_REPO}/mi-medcare-api:$COMMIT_SHA"

substitutions:
  _AR_HOST: "asia-south1-docker.pkg.dev"
  _AR_REPO: "mi-medcare"
