import {
  IconChartBar,
  IconFileText,
  IconShieldCheck,
  IconRosetteDiscountCheck,
  IconClipboardCheck,
  IconAlertTriangle,
  IconWallet,
  IconCpu,
  IconChartLine,
  IconPlug,
  IconBook,
  IconBriefcase,
  IconMessageCircle,
  IconHelpCircle,
  IconUserPlus,
  IconHeartbeat,
  IconBolt,
  IconWorld,
  IconLock,
  IconUsersGroup,
  IconShield,
  IconClock,
  IconSparkles,
} from "@tabler/icons-react";

import {
  TrendingUp,
  Clock,
  Zap,
  HeartHandshake,
  FileText,
  CheckCircle,
  ArrowUpCircle,
  BarChart,
  Brain,
  Baby,
  Footprints,
  Activity,
  Droplet,
  Smile,
  Stethoscope,
  Moon,
  Syringe,
  Hand,
  Shield,
  Eye,
  Ear,
  Wind,
  Mic,
  Scissors,
  Dumbbell,
  Network,
  HeartPulse,
  Microscope,
  Flame,
  Bug,
  Users,
  Hospital,
  Apple,
  Radio,
  ClipboardCheck,
  UserCheck,
  Send,
  Wallet,
  BarChart3,
} from "lucide-react";

export const IconMap = {
  /* tabler */
  chartBar: IconChartBar,
  fileTextTabler: IconFileText,
  shieldCheck: IconShieldCheck,
  rosetteDiscountCheck: IconRosetteDiscountCheck,
  clipboardCheckTabler: IconClipboardCheck,
  alertTriangle: IconAlertTriangle,
  walletTabler: IconWallet,
  cpu: IconCpu,
  chartLine: IconChartLine,
  plug: IconPlug,
  book: IconBook,
  briefcase: IconBriefcase,
  messageCircle: IconMessageCircle,
  helpCircle: IconHelpCircle,
  userPlus: IconUserPlus,
  heartbeat: IconHeartbeat,
  bolt: IconBolt,
  world: IconWorld,
  lock: IconLock,
  usersGroup: IconUsersGroup,
  shield: IconShield,
  clockTabler: IconClock,
  sparkles: IconSparkles,

  /* lucide */
  trendingUp: TrendingUp,
  clock: Clock,
  zap: Zap,
  heartHandshake: HeartHandshake,
  fileText: FileText,
  checkCircle: CheckCircle,
  arrowUpCircle: ArrowUpCircle,
  barChart: BarChart,
  brain: Brain,
  baby: Baby,
  footprints: Footprints,
  activity: Activity,
  droplet: Droplet,
  smile: Smile,
  stethoscope: Stethoscope,
  moon: Moon,
  syringe: Syringe,
  hand: Hand,
  shieldLucide: Shield,
  eye: Eye,
  ear: Ear,
  wind: Wind,
  mic: Mic,
  scissors: Scissors,
  dumbbell: Dumbbell,
  network: Network,
  heartPulse: HeartPulse,
  microscope: Microscope,
  flame: Flame,
  bug: Bug,
  users: Users,
  hospital: Hospital,
  apple: Apple,
  radio: Radio,
  clipboardCheck: ClipboardCheck,
  userCheck: UserCheck,
  send: Send,
  wallet: Wallet,
  barChart3: BarChart3,
} as const;
